### ISSUE TITLE
hi, is this still need it?

### ISSUE THREAD

**Issue by iosub** [lalanikarim/tool_calling_llm#3]
hi.

Im using this "patch" for _with_structured.. do you is is still need it or Langchain.ollama has fixit or planning to fix?

Thanks for your work

**Comment by lalanikarim** [comment]
You no longer need it if you are using the ChatOllama from the latest [langchain-ollama](https://pypi.org/project/langchain-ollama/) package and your llm is supported for tool use by Ollama.
There are still a few models that are capable of tool use on Ollama but aren't supported by them yet. Until they are supported by, you can continue to use [tool-calling-llm](https://pypi.org/project/tool-calling-llm/).
